name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy heroku
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), 'skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "poke-dex-site" #Must be unique in Heroku
          heroku_email: "prana12@live.com"
          healthcheck: "https://poke-dex-site.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: git checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), 'skip')}}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Notification success
        if: ${{ success() && github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: 8398a7/action-slack@v3
        with:
            status: custom
            # fields: commit,repo,author,workflow,took
            # text: `A new version of ${process.env.AS_REPO} deployed, commit: (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} with the ${process.env.AS_WORKFLOW} workflow (Time used: ${process.env.AS_TOOK})`
            fields: workflow,job,commit,repo,ref,author,took
            custom_payload: |
              {
                attachments: [{
                  color: 'good', 
                  text: `{process.env.AS_WORKFLOW} - ${{ job.status }}\nA new version is deployed with job {process.env.AS_JOB}(commit: ${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} (Time used: ${process.env.AS_TOOK})`
                }]
              }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notification failure
        if: ${{ failure() && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: 8398a7/action-slack@v3
        with:
            status: ${{ job.status }}
            # fields: all
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
            # status: custom
            # fields: workflow,job,commit,repo,ref,author,took
            # custom_payload: |
            #   {
            #     attachments: [{
            #       color: 'danger' 
            #       text: `${process.env.AS_WORKFLOW} failed: {process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            #     }]
            #   }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
